### PR TITLE
Add skeleton of the controller + vendoring

### PR DESCRIPTION
**Pull request by jsafrane**

### CODE REVIEW

**Comment by jsafrane** [comment]
testing what bots do we have here...

/bark
/kind feature
/priority important-soon

**Comment by pohly** [comment]
The `release-note` plugin is not active. It can be added to: https://github.com/pohly/test-infra/blob/ab0120cf42df1549319c9bc664b91dfb2bce5ac7/prow/plugins.yaml#L484-L505

And what the heck is `blunderbuss`?

/blunderbuss

**Comment by jsafrane** [comment]
> The release-note plugin is not active

Yeah, I know. I was checking just in case :-).

/meow

**Comment by msau42** [comment]
Blunderbuss I think is the bot that assigns reviewers to prs

**Pull request merged**
